### ISSUE TITLE
Provide range for each category

### ISSUE THREAD

**Issue by antonyclinton769** [Thejus-Paul/Project-Apollonir#7]
1. Corportates/.../ : 101-500
2. Educational Institutions : 500 - 1000
3. Hospitals : 1001-1500
4. NGO : 1501-2000
5. Study Abroad : 2001-2500

In total, 2500 company entries from all 5 categories.

While making each entry under a category the id has to be incremented and decremented if deleted at some point of time.

**Comment by Thejus-Paul** [comment]
So, instead of defining an exact range like 101-500, why can't we use a counter for all 5 categories.
When the counter reaches 0, then we have to delete a company from that category in order to add a new entry.

**Comment by antonyclinton769** [comment]
I didnt think of that.Sorry.
